name: deploy-and-migrate

on:
  workflow_dispatch: 
  push:
    branches: [ main ]  

env:
  DOTNET_VERSION: '8.0.100'

jobs:
  migrate-database:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Install EF Core CLI
      run: dotnet tool install --global dotnet-ef

    - name: Add EF CLI to PATH
      run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

    - name: Run EF Core migrations
      env:
        CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
      run: |
        dotnet ef database update \
          --startup-project ./TravelAndAccommodationBookingPlatform.API \
          --project ./TravelAndAccommodationBookingPlatform.Infrastructure \
          --connection "$CONNECTION_STRING"